[tool.poetry]
name = "laptime_sim"
version = "0.1.0"
description = ""
authors = ["JanJaapvandeVelde <janjaap.vandevelde@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.31.1"
geopandas = "^0.14.3"
streamlit-folium = "^0.18.0"
plotly = "^5.19.0"
folium = "^0.16.0"
matplotlib = "^3.8.1"
mapclassify = "^2.6.1"
pyogrio = "^0.7.2"
altair = "^5.2.0"

[tool.poetry.group.test.dependencies]
pytest = "*"
icecream = "*"
flake8 = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

