[tool.poetry]
name = "laptime_sim"
version = "0.1.0"
description = ""
authors = ["JanJaapvandeVelde <janjaap.vandevelde@gmail.com>"]
readme = "README.md"
# packages = [{include = "laptime_sim", from = "src"}]
# packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.28.2"
geopandas = "^0.14.1"
streamlit-folium = "^0.16.0"
plotly = "^5.17.0"
folium = "^0.14.0"
matplotlib = "^3.8.1"
mapclassify = "^2.6.1"
pyogrio = "^0.7.2"
altair = "^5.2.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
icecream = "^2.1.3"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
# addopts = ["--import-mode=importlib",]
pythonpath = ["src"]
